title: Rohan Singh
# logo: 
description: Hi, my name is Rohan Singh. I'm a high school senior passionate about computer science and artificial intelligence (AI). I am eager to explore more in the AI and machine learning field and develop innovative solutions to real-world problems. I am seeking opportunities to expand my knowledge, gain hands-on experience, and connect with like-minded individuals in the field.
show_downloads: true
theme: jekyll-theme-minimal
